### PR TITLE
Add More Conversion 

### PR DESCRIPTION
**Pull request by IHaveNoZpu**

### CODE REVIEW

**Comment by scientific-dev** [comment]
Looks good to me, here are some few doubts,

Is this supposed to be `Cmyk` or `Cmyx`?

https://github.com/scientific-dev/colormath.js/blob/1f836a8a8609016628bf925a327226d243d3a977/src/convert.ts#L575

And conversion from `Gray` to `Hex` seems useless since the working is similar as `Gray` to `Rgb` to `Hex`. But, still is `Gray` to `Hex` necessary?. The main reason to keep less conversions so that the module can be light. 

https://github.com/scientific-dev/colormath.js/blob/1f836a8a8609016628bf925a327226d243d3a977/src/convert.ts#L583-L589

**Comment by IHaveNoZpu** [comment]
> Is this supposed to be Cmyk or Cmyx?

It Cmyk. im sorry my keyboard is suck

>  And conversion from Gray to Hex seems useless since the working is similar as Gray to Rgb to Hex. But, still is Gray to Hex necessary?. The main reason to keep less conversions so that the module can be light.

Idk for me i think it necessary. you can remove it if you want

**Comment by scientific-dev** [comment]
Then everything looks fine.

**Comment by scientific-dev** [comment]
These changes have updated to [Colormath.js v1.1.0](https://github.com/scientific-dev/colormath.js/releases/tag/1.1.0).

**Pull request merged**
